apiVersion: apiserver.config.k8s.io/v1alpha1
kind: AuthenticationConfiguration
jwt:
- issuer:
    url: https://oidc-discovery-provider.${SPIFFE_TRUST_DOMAIN}
    discoveryURL: https://k8ssodp.${SPIFFE_TRUST_DOMAIN}:8181/.well-known/openid-configuration
    audiences:
    - k8s-one
  claimMappings:
    username:
      expression: |
        claims.sub.startsWith("spiffe://${SPIFFE_TRUST_DOMAIN}/k8s/one/node/")? claims.sub.replace("spiffe://${SPIFFE_TRUST_DOMAIN}/k8s/one/node/", "system:node:").replace(".${SPIFFE_TRUST_DOMAIN}", ""): claims.sub
    groups:
      expression: |
        claims.sub.startsWith("spiffe://${SPIFFE_TRUST_DOMAIN}/k8s/one/node/")? ["system:nodes"]: []
